version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: 'on'
    working_directory: /tmp/codf
    steps:
      - checkout
      - run: go build -v .
      - run: go test -coverprofile=cover.out -covermode=atomic .
      - run: go tool cover -func=cover.out
      - run: bash <(curl -s https://codecov.io/bash) -f cover.out
